image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet build
    - dotnet test

publish:
  stage: publish
  script:
    - dotnet build
    - dotnet publish
    - dotnet nuget push DriveSupplyCollectorBase/bin/Debug/*.nupkg -k $NUGET_KEY -s https://www.myget.org/F/s2/api/v2/package

